[jobs.check]
command = ["cargo", "check", "--all-targets", "--all-features"]
need_stdout = false

[jobs.clippy]
command = ["cargo", "clippy", "--all-targets", "--all-features", "--", "-D", "warnings"]
need_stdout = false

[jobs.test]
command = ["cargo", "nextest", "run", "--all-features", "--no-tests=pass"]
need_stdout = true

[jobs.doc]
command = ["cargo", "doc", "--no-deps", "--all-features"]
need_stdout = false
env.RUSTDOCFLAGS = "-D warnings"

[keybindings]
c = "job:check"
l = "job:clippy"
t = "job:test"
d = "job:doc"
