[check]
command = "clippy"
allTargets = true
allFeatures = true
extraArgs = ["--", "-D", "warnings"]

[diagnostics]
warningsAsHint = []
warningsAsInfo = []

[imports]
granularity.group = "crate"
prefix = "self"

[completion]
fullFunctionSignatures.enable = true
postfix.enable = true

[inlayHints]
closingBraceHints.minLines = 15
parameterHints.enable = true
typeHints.enable = true
chainingHints.enable = true
lifetimeElisionHints.enable = "always"
